export const products = [
    {
      "id": "1",
      "name": "Gabi For Men",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 30,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 0,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/gabi_1.png"
    },
    {
      "id": "2",
      "name": "Habesha Kemis",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 40,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 60,
      "currency": "USD",
      "size": 0,
      "quantity": 30,
      "url": "/habesha_kemis_1.png",
    },
    {
      "id": "3",
      "name": "Gabi For Men",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 40,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 90,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/gabi_2.png"
    },
    {
      "id": "4",
      "name": "Traditional Ethiopian Habesha Kemis",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 40,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 90,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/habesh_kemis.png"
    },
    {
      "id": "5",
      "name": "Traditional Ethiopian Drum",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 70,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 56,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/kebero_1.png"
    },
    {
      "id": "6",
      "name": "Traditional Clothe For Men",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 70,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 56,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/men_1.png"
    },
    {
      "id": "7",
      "name": "Habesha Kemis",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 70,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 56,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "product_id": "fcc00e34-813e-4fa7-b90e-8a79cac111fe",
      "url": "/habesha_kemis_2.png"
    },
    {
      "id": "8",
      "name": "Ethiopian Kirar",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 40,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 60,
      "currency": "USD",
      "size": 0,
      "quantity": 30,
      "url": "/kirar_1.png",
    },
    {
      "id": "9",
      "name": "Traditional Cloth For Men",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 40,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 90,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/habesha_men.png"
    },
    {
      "id": "10",
      "name": "Traditional Ethiopian Habesha Kemis",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 40,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 90,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/habesha_kemis_3.png"
    },
    {
      "id": "11",
      "name": "Traditional Ethiopian Drum",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 70,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 56,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/kebero_2.png"
    },
    {
      "id": "12",
      "name": "Traditional Men Cloth",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 70,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 56,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "url": "/men_2.png"
    },
    {
      "id":"13",
      "name": "Traditional Mesenko",
      "description": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "price": 70,
      "more_info": "This vibrant basket is made using traditional weaving techniques and can be used for storage or decoration.",
      "category": "string",
      "weight": 56,
      "currency": "USD",
      "size": 0,
      "quantity": 10,
      "product_id": "fcc00e34-813e-4fa7-b90e-8a79cac111fe",
      "url": "/mesenko.png"
    }
  ]